### ISSUE TITLE
Python error on line 119 in idaref.py at launch, on IDA 6.8

### ISSUE THREAD

**Issue by michael-myers** [nologic/idaref#11]
Windows 10, IDA 6.8 x64

When IDA Pro is launched, it displays a dialog box, with the message:

> idaref.py: invalid syntax ...
> File "C:/Program Files (x86)/IDA 6.8/plugins/idaref.py", line 119
> if(not os.path.isfile(dbpath)):
> .............................^
> SyntaxError: invalid syntax

Looks like a closed paren typo on line 118, as referenced in this pull request https://github.com/nologic/idaref/pull/10

**Comment by nologic** [comment]
PR merged.
