### ISSUE TITLE
missing x86 aliases

### ISSUE THREAD

**Issue by bnagy** [nologic/idaref#3]
Hi!

There are a lot of redirects missing in your .sql. While I was writing https://github.com/bnagy/cgasm I wrote a code generator to convert your .sql to a go map. Once that was done it was no trouble to add your original .sql format as an alternate output format. You can generate a cleaner .sql file for this project by running this: https://github.com/bnagy/cgasm/tree/master/codegen

```
sqlgen sql > name_of_file.sql
```

The new .sql also has explicit redirects for all Jcc variants etc, so you shouldn't need to special case those anymore.

Let me know if the tool doesn't work for you for any reason (I didn't test, I just visually compared the SQL)

Cheers!

**Comment by nologic** [comment]
Many thanks for the suggestion. I'll check it out and see if it simplifies things.

**Comment by mrexodia** [comment]
I wrote some special cases for the aliasing. This function gets a 'universal' mnemonic (eg handle `XXcc`)

``` c++
String MnemonicHelp::getUniversalMnemonic(const String & mnem)
{
    auto mnemLower = StringUtils::ToLower(mnem);
    auto startsWith = [&](const char* n)
    {
        return StringUtils::StartsWith(mnemLower, n);
    };
    if(mnemLower == "jmp")
        return mnemLower;
    if(mnemLower == "loop")  //LOOP
        return mnemLower;
    if(startsWith("int"))  //INT n
        return "int n";
    if(startsWith("cmov"))  //CMOVcc
        return "cmovcc";
    if(startsWith("fcmov"))  //FCMOVcc
        return "fcmovcc";
    if(startsWith("j"))  //Jcc
        return "jcc";
    if(startsWith("loop"))  //LOOPcc
        return "loopcc";
    if(startsWith("set"))  //SETcc
        return "setcc";
    return mnemLower;
}
```

Then there is another special case to handle virtual/vector (not sure) instructions (when not found in the database) and redirections:

``` c++
String MnemonicHelp::getDescription(const char* mnem, int depth)
{
    if(mnem == nullptr)
        return "Invalid mnemonic!";
    if(depth == 10)
        return "Too many redirections...";
    SHARED_ACQUIRE(LockMnemonicHelp);
    auto mnemuni = getUniversalMnemonic(mnem);
    auto found = MnemonicMap.find(mnemuni);
    if(found == MnemonicMap.end())
    {
        if(mnemuni[0] == 'v')  //v/vm
        {
            found = MnemonicMap.find(mnemuni.c_str() + 1);
            if(found == MnemonicMap.end())
                return "";
        }
        else
            return "";
    }
    const auto & description = found->second;
    if(StringUtils::StartsWith(description, "-R:"))  //redirect
    {
        SHARED_RELEASE();
        return getDescription(description.c_str() + 3, depth + 1);
    }
    return description;
}
```

Might be useful for some people.

**Comment by nologic** [comment]
Thanks for that, I shall incorporate

**Comment by nologic** [comment]
Just looking over some unclosed issues. I'm a little confused by this part:

``` c++
if(found == MnemonicMap.end())
    {
        if(mnemuni[0] == 'v')  //v/vm
        {
            found = MnemonicMap.find(mnemuni.c_str() + 1);
            if(found == MnemonicMap.end())
                return "";
        }
        else
            return "";
    }
```

Are you saying that if a V[blah] instruction is not found then the documentation for [blah](for example, VERR -> ERR) is the valid option?

**Comment by mrexodia** [comment]
Yes that's what I'm doing. I don't have an example opcode but the Intel
part says blah/vblah in there.

**Comment by nologic** [comment]
I've updated this by expanding the mnemonics, hopefully we now have all the instructions.
